baseURL: https://virusbb001.github.io/
disablePathToLower: true
languageCode: "ja"
defaultContentLanguage: "ja"
hasCJKLanguage: true
theme: "hyde-x"
relativeURLs: true
permalinks:
  post: /blog/:year/:month/:day/:filename/
PygmentsCodeFences: true
pygmentsstyle: "friendly"
title: "virusbb001's blog"
disqusShortName: "virusbb001githubio"

author:
  name: "virusbb001"
